### ISSUE TITLE
TimeToFirstResponse regression with latest npgsql

### ISSUE THREAD

**Issue by sebastienros** [aspnet/Benchmarks#1922] opened 2023-10-27 16:30 UTC
![image](https://github.com/aspnet/Benchmarks/assets/1165805/d05d1dbb-d6da-4bf2-b8ee-42a0fd97eccc)

@roji

**Comment by roji** [comment] 2023-10-27 16:39
Thanks @sebastienros. This represents an application startup time only, triggered when we switched from Npgsql 8.0.0-preview.4 to rc.2, right?

/cc @NinoFloris @vonzshik

**Comment by DamianEdwards** [comment] 2023-10-27 16:40
Technically it's first response, so likely caused by first time Npgsql types are initialized via DI.

**Comment by vonzshik** [comment] 2023-10-27 16:44
Curiously, the platform ones didn't regress, just the default (`Fortunes`, `FortunesDapper` and `FortunesEf`).

**Comment by sebastienros** [comment] 2023-10-27 16:45
Platform is not using DI. NativeAOT benchmarks are also impacted.

**Comment by vonzshik** [comment] 2023-10-27 17:43
Ignoring DI for a moment, I can see that for a simple HelloWorld app we spent quite a bit of time in [JsonTypeInfoResolver](https://github.com/npgsql/npgsql/blob/7bc04bcc09de8463ac7c2bd435ea15c336114b86/src/Npgsql/Internal/Resolvers/JsonTypeInfoResolvers.cs#L22):

![image](https://github.com/aspnet/Benchmarks/assets/14861420/160feef1-e8cc-4da9-8993-09ab200c9d18)

and 90% of that is jit-compiling something while accessing `JsonSerializerOptions.Default`:

![image](https://github.com/aspnet/Benchmarks/assets/14861420/258e133a-7e94-4aa7-9835-b1e1fcb650bf)

**Comment by NinoFloris** [comment] 2023-10-29 17:13
>Curiously, the platform ones didn't regress, just the default (Fortunes, FortunesDapper and FortunesEf).

Given this is the case we're very likely looking at our non-slim config being responsible for most of the extra work.
JsonSerializerOptions.Default seems like a good candidate to start with.

PlatformDapper and PlatformEf do show a slight increase in TTFR so there is a bit more work done at minimum as well; will have to benchmark to figure out the exact origin. I expect some part of it to come down to the increase in component/method count making up our pg type handling infra after atomizing it for NativeAOT and trimming. This would add JIT time *and* runtime cost to create the larger object graphs.

Will see what we can do to reduce the baseline somewhat, together with some other performance improvements we still have planned for 8.0. Though to set expectations, it'll more likely will be 8(.0).1 before we get to it.

For now I have a fix out for the JIT cost incurred from eagerly accessing JsonSerializerOptions.Default (thanks for the profile @vonzshik) https://github.com/npgsql/npgsql/pull/5359

**Comment by roji** [comment] 2023-11-01 17:31
OK, did some perf runs. rc.2 and 6b1e70c6 (last commit before https://github.com/npgsql/npgsql/pull/5359) have TTFR *367ms* and *354ms* respectively. https://github.com/npgsql/npgsql/pull/5359 doesn't seem to have a noticeable effect (348ms), but switching to lazy mapping (https://github.com/npgsql/npgsql/pull/5360) brings us back down to *285ms*, which I think is where we were before the move to rc.2 (🎉)

Note that for platform benchmarks we should switch to the slim builder. I think it's good to stay on the regular builder for the non-platform benchmarks so that we have benchmark coverage for it, and it's what most people are likely to use.

### rc.2 (baseline)

<details>
<summary>rc.2 (baseline)</summary>

```
crank --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/scenarios/database.benchmarks.yml --scenario fortunes --profile aspnet-citrine-lin --application.framework net9.0 --application.options.outputFiles C:\projects\npgsql\src\Npgsql\bin\Release\net8.0\Npgsql.dll --json c:\temp\benchmarks\FortunesPlatform\v8.0.0-rc.2.json
```
```
| db                   |         |
| -------------------- | ------- |
| Max CPU Usage (%)    | 33      |
| Max Cores usage (%)  | 918     |
| Max Working Set (MB) | 54      |
| Build Time (ms)      | 1,482   |
| Start Time (ms)      | 1,088   |
| Published Size (KB)  | 368,923 |


| application             |                                    |
| ----------------------- | ---------------------------------- |
| Max CPU Usage (%)       | 97                                 |
| Max Cores usage (%)     | 2,708                              |
| Max Working Set (MB)    | 521                                |
| Max Private Memory (MB) | 1,268                              |
| Build Time (ms)         | 5,595                              |
| Start Time (ms)         | 202                                |
| Published Size (KB)     | 120,762                            |
| Symbols Size (KB)       | 57                                 |
| .NET Core SDK Version   | 9.0.100-alpha.1.23551.8            |
| ASP.NET Core Version    | 9.0.0-alpha.1.23551.2+508c049e0821 |
| .NET Runtime Version    | 9.0.0-alpha.1.23551.4+8bce5a83af2c |


| load                    |                     |
| ----------------------- | ------------------- |
| Max CPU Usage (%)       | 34                  |
| Max Cores usage (%)     | 962                 |
| Max Working Set (MB)    | 49                  |
| Max Private Memory (MB) | 358                 |
| Build Time (ms)         | 3,330               |
| Start Time (ms)         | 0                   |
| Published Size (KB)     | 73,211              |
| Symbols Size (KB)       | 0                   |
| .NET Core SDK Version   | 7.0.403             |
| ASP.NET Core Version    | 7.0.13+d634f2bd1ad6 |
| .NET Runtime Version    | 7.0.13+3f73a2f186e0 |
| First Request (ms)      | 367                 |
| Requests/sec            | 393,110             |
| Requests                | 5,935,798           |
| Mean latency (ms)       | 0.70                |
| Max latency (ms)        | 24.28               |
| Bad responses           | 0                   |
| Socket errors           | 0                   |
| Read throughput (MB/s)  | 512.49              |
| Latency 50th (ms)       | 0.59                |
| Latency 75th (ms)       | 0.83                |
| Latency 90th (ms)       | 1.05                |
| Latency 99th (ms)       | 2.74                |
```

</details>

<details>
<summary>Before PR replacing DefaultJsonTypeInfoResolver #5359 (6b1e70c6)</summary>

```
crank --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/scenarios/database.benchmarks.yml --scenario fortunes --profile aspnet-citrine-lin --application.framework net9.0 --application.options.outputFiles C:\projects\npgsql\src\Npgsql\bin\Release\net8.0\Npgsql.dll --json c:\temp\benchmarks\FortunesPlatform\6b1e70c6.json
```
```
| db                   |         |
| -------------------- | ------- |
| Max CPU Usage (%)    | 33      |
| Max Cores usage (%)  | 928     |
| Max Working Set (MB) | 54      |
| Build Time (ms)      | 1,319   |
| Start Time (ms)      | 1,078   |
| Published Size (KB)  | 368,923 |


| application             |                                    |
| ----------------------- | ---------------------------------- |
| Max CPU Usage (%)       | 96                                 |
| Max Cores usage (%)     | 2,688                              |
| Max Working Set (MB)    | 531                                |
| Max Private Memory (MB) | 1,280                              |
| Build Time (ms)         | 6,790                              |
| Start Time (ms)         | 204                                |
| Published Size (KB)     | 120,762                            |
| Symbols Size (KB)       | 57                                 |
| .NET Core SDK Version   | 9.0.100-alpha.1.23551.8            |
| ASP.NET Core Version    | 9.0.0-alpha.1.23551.5+864200433477 |
| .NET Runtime Version    | 9.0.0-alpha.1.23551.4+8bce5a83af2c |


| load                    |                     |
| ----------------------- | ------------------- |
| Max CPU Usage (%)       | 35                  |
| Max Cores usage (%)     | 968                 |
| Max Working Set (MB)    | 48                  |
| Max Private Memory (MB) | 358                 |
| Build Time (ms)         | 3,308               |
| Start Time (ms)         | 0                   |
| Published Size (KB)     | 73,211              |
| Symbols Size (KB)       | 0                   |
| .NET Core SDK Version   | 7.0.403             |
| ASP.NET Core Version    | 7.0.13+d634f2bd1ad6 |
| .NET Runtime Version    | 7.0.13+3f73a2f186e0 |
| First Request (ms)      | 354                 |
| Requests/sec            | 387,677             |
| Requests                | 5,853,757           |
| Mean latency (ms)       | 0.71                |
| Max latency (ms)        | 17.50               |
| Bad responses           | 0                   |
| Socket errors           | 0                   |
| Read throughput (MB/s)  | 505.40              |
| Latency 50th (ms)       | 0.60                |
| Latency 75th (ms)       | 0.84                |
| Latency 90th (ms)       | 1.06                |
| Latency 99th (ms)       | 2.75                |
```
</details>

<details>
<summary>After replacing DefaultJsonTypeInfoResolver #5359 (1530dee1)</summary>

```
crank --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/scenarios/database.benchmarks.yml --scenario fortunes --profile aspnet-citrine-lin --application.framework net9.0 --application.options.outputFiles C:\projects\npgsql\src\Npgsql\bin\Release\net8.0\Npgsql.dll --json c:\temp\benchmarks\FortunesPlatform\1530dee1.json
```
```
| db                   |         |
| -------------------- | ------- |
| Max CPU Usage (%)    | 33      |
| Max Cores usage (%)  | 927     |
| Max Working Set (MB) | 55      |
| Build Time (ms)      | 1,390   |
| Start Time (ms)      | 1,180   |
| Published Size (KB)  | 368,923 |


| application             |                                    |
| ----------------------- | ---------------------------------- |
| Max CPU Usage (%)       | 96                                 |
| Max Cores usage (%)     | 2,695                              |
| Max Working Set (MB)    | 529                                |
| Max Private Memory (MB) | 1,278                              |
| Build Time (ms)         | 4,103                              |
| Start Time (ms)         | 197                                |
| Published Size (KB)     | 120,762                            |
| Symbols Size (KB)       | 57                                 |
| .NET Core SDK Version   | 9.0.100-alpha.1.23551.8            |
| ASP.NET Core Version    | 9.0.0-alpha.1.23551.5+864200433477 |
| .NET Runtime Version    | 9.0.0-alpha.1.23551.4+8bce5a83af2c |


| load                    |                     |
| ----------------------- | ------------------- |
| Max CPU Usage (%)       | 35                  |
| Max Cores usage (%)     | 966                 |
| Max Working Set (MB)    | 48                  |
| Max Private Memory (MB) | 358                 |
| Build Time (ms)         | 3,364               |
| Start Time (ms)         | 0                   |
| Published Size (KB)     | 73,211              |
| Symbols Size (KB)       | 0                   |
| .NET Core SDK Version   | 7.0.403             |
| ASP.NET Core Version    | 7.0.13+d634f2bd1ad6 |
| .NET Runtime Version    | 7.0.13+3f73a2f186e0 |
| First Request (ms)      | 348                 |
| Requests/sec            | 385,780             |
| Requests                | 5,825,075           |
| Mean latency (ms)       | 0.71                |
| Max latency (ms)        | 12.76               |
| Bad responses           | 0                   |
| Socket errors           | 0                   |
| Read throughput (MB/s)  | 502.93              |
| Latency 50th (ms)       | 0.60                |
| Latency 75th (ms)       | 0.84                |
| Latency 90th (ms)       | 1.07                |
| Latency 99th (ms)       | 2.78                |
```
</details>

<details>
<summary>With lazy mapping setup PR #5360 (3152b614)</summary>

```
crank --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/scenarios/database.benchmarks.yml --scenario fortunes --profile aspnet-citrine-lin --application.framework net9.0 --application.options.outputFiles C:\projects\npgsql\src\Npgsql\bin\Release\net8.0\Npgsql.dll --json c:\temp\benchmarks\FortunesPlatform\3152b614.json
```
```
| db                   |         |
| -------------------- | ------- |
| Max CPU Usage (%)    | 33      |
| Max Cores usage (%)  | 936     |
| Max Working Set (MB) | 52      |
| Build Time (ms)      | 1,272   |
| Start Time (ms)      | 1,125   |
| Published Size (KB)  | 368,923 |


| application             |                                    |
| ----------------------- | ---------------------------------- |
| Max CPU Usage (%)       | 96                                 |
| Max Cores usage (%)     | 2,701                              |
| Max Working Set (MB)    | 520                                |
| Max Private Memory (MB) | 1,270                              |
| Build Time (ms)         | 4,355                              |
| Start Time (ms)         | 195                                |
| Published Size (KB)     | 120,762                            |
| Symbols Size (KB)       | 57                                 |
| .NET Core SDK Version   | 9.0.100-alpha.1.23551.8            |
| ASP.NET Core Version    | 9.0.0-alpha.1.23551.5+864200433477 |
| .NET Runtime Version    | 9.0.0-alpha.1.23551.4+8bce5a83af2c |


| load                    |                     |
| ----------------------- | ------------------- |
| Max CPU Usage (%)       | 34                  |
| Max Cores usage (%)     | 961                 |
| Max Working Set (MB)    | 48                  |
| Max Private Memory (MB) | 358                 |
| Build Time (ms)         | 3,314               |
| Start Time (ms)         | 0                   |
| Published Size (KB)     | 73,211              |
| Symbols Size (KB)       | 0                   |
| .NET Core SDK Version   | 7.0.403             |
| ASP.NET Core Version    | 7.0.13+d634f2bd1ad6 |
| .NET Runtime Version    | 7.0.13+3f73a2f186e0 |
| First Request (ms)      | 285                 |
| Requests/sec            | 393,083             |
| Requests                | 5,935,415           |
| Mean latency (ms)       | 0.70                |
| Max latency (ms)        | 21.70               |
| Bad responses           | 0                   |
| Socket errors           | 0                   |
| Read throughput (MB/s)  | 512.45              |
| Latency 50th (ms)       | 0.59                |
| Latency 75th (ms)       | 0.83                |
| Latency 90th (ms)       | 1.04                |
| Latency 99th (ms)       | 2.70                |
```

</summary>

**Comment by roji** [comment] 2023-11-01 17:50
FYI just submitted #1925 for switch to NpgsqlSlimDataSourceBuilder for the platform benchmarks only (so will not affect the above, which is non-platform). This removes quite a bit of setup and types, a quick manual test shows **100ms** for TTFR.

**Comment by roji** [comment] 2023-11-03 10:22
Closing as this was fixed via https://github.com/npgsql/npgsql/pull/5360

**Closed by roji** 2023-11-03 10:22 UTC
