### ISSUE TITLE
Bad responses: ResponseCachingPlaintextCachedDelete, ResponseCachingPlaintextCachedDelete

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Benchmarks#648] opened 2019-02-15 02:51 UTC
Some scenarios return errors:

| Scenario | Environment | Last Run | Errors |
| -------- | ----------- | -------- | ------ |
| ResponseCachingPlaintextCachedDelete | Linux, Physical, http, KestrelSockets | 2/15/19 12:28:04 AM +00:00 | 55977346 |
| ResponseCachingPlaintextCachedDelete | Linux, Cloud, http, KestrelSockets | 2/15/19 12:32:54 AM +00:00 | 8383294 |

**Comment by davidfowl** [comment] 2019-02-18 06:17
This one looks legit broken:

```
RequestsPerSecond:           3781677
Max CPU (%):                 97
WorkingSet (MB):             512
Avg. Latency (ms):           1
Startup (ms):                277
First Request (ms):          40
Latency (ms):                0.2
Total Requests:              57103603
Duration: (ms)               15100
Socket Errors:               0
Bad Responses:               57103603
SDK:                         3.0.100-preview4-010371
Runtime:                     3.0.0-preview3-27414-8
ASP.NET Core:                3.0.0-preview3-19117-03
```

Every single request failed.

**Comment by davidfowl** [comment] 2019-02-18 06:34
Requests are returning a 0 status code:

```
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 DELETE http://10.0.0.110:5000/responsecaching/plaintext/cached
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 0.3724ms 0
```

Which gets set here https://github.com/aspnet/AspNetCore/blob/3e47fa7c693447f7ad6c0ef7620ee81c12b730f5/src/Servers/Kestrel/Core/src/Internal/Http/HttpProtocol.cs#L636.

**Comment by davidfowl** [comment] 2019-02-18 06:56
I can't seem to reproduce it in isolation but it's likely this code path:

https://github.com/aspnet/AspNetCore/blob/3e47fa7c693447f7ad6c0ef7620ee81c12b730f5/src/Middleware/ResponseCaching/src/ResponseCachingMiddleware.cs#L176-L188

**Comment by davidfowl** [comment] 2019-02-18 08:08
Raw dump here https://gist.github.com/davidfowl/2e396efa55efa37b3944dcc1aae0b475

**Comment by davidfowl** [comment] 2019-02-18 08:09
Looks like it's actually a bunch of 404s...

**Comment by sebastienros** [comment] 2019-02-18 15:03
I fixed one of them last week, the scenario name didn't match so the middle was not enabled.

**Comment by davidfowl** [comment] 2019-02-20 05:20
Same here?

**Closed** 2019-05-17 22:22 UTC
Labels: bad-response
