### ISSUE TITLE
Performance regression: DbMultiUpdateDapper

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Benchmarks#545] opened 2018-10-28 00:50 UTC
A performance regression has been detected for the following scenarios:

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| DbMultiUpdateDapper | Linux, http, KestrelSockets | 2018-10-28 00:48:25Z | 1597 | 1513 | -5.26 % | -2.25 σ |

Before versions:
Microsoft.AspNetCore.App __2.2.0-rtm-35545__
Microsoft.NetCore.App __2.2.0-preview3-27014-02__

After versions:
Microsoft.AspNetCore.App __2.2.0-rtm-35580__
Microsoft.NetCore.App __2.2.0-preview3-27014-02__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/Universe/compare/5acbb9d138f388d49efb800edd5a3df609f77d46...373e67896ab5ef157234971a0008011a257e17a1

**Comment by sebastienros** [comment] 2018-11-05 17:49
Duplicate of #554

**Closed by sebastienros** 2018-11-05 17:49 UTC
