### ISSUE TITLE
Profile a basic WebListener scenario

### ISSUE THREAD

**Issue by Eilon** [aspnet/benchmarks#21] opened 2015-10-13 21:31 UTC

**Comment by DamianEdwards** [comment] 2016-02-12 06:25
We should add numbers for WebListener for all the scenarios. The server can be passed in at execution time on the command line or set with a hosting.json file so it's already pluggable (yay ASP.NET Core!).

**Comment by dougbu** [comment] 2017-01-28 02:14
Is this yet-another dupe of #112?

**Comment by mikeharder** [comment] 2017-01-28 02:29
@dougbu: yep

**Closed** 2017-01-28 02:42 UTC
Labels: duplicate
